### ISSUE TITLE
Why does React have to be included in src/index.html.ejs?

### ISSUE THREAD

**Issue by Ahimta** [vikpe/react-webpack-typescript-starter#3]
Why does React have to be included in `src/index.html.ejs` and shouldn't it be included just through regular imports?

**Comment by vikpe** [comment]
@Ahimta I've chosen to include the React/ReactDOM libs from a CDN instead of including them in the build.

This reduces build time during development and load time for users as there is a high chance that they already have React/ReactDOM in their browser cache.

In webpack termonology it's called [externals](https://webpack.js.org/configuration/externals/) and is defined in the webpack config.

> The externals configuration option provides a way of excluding dependencies from the output bundles. Instead, the created bundle relies on that dependency to be present in the consumer's environment. 

In this repo I've configured it in [`/configs/webpack/common.js`](https://github.com/vikpe/react-webpack-typescript-starter/blob/master/configs/webpack/common.js):
```javascript
 externals: {
    'react': 'React',
    'react-dom': 'ReactDOM',
  },
```

**Comment by Ahimta** [comment]
Makes sense.
