### ISSUE TITLE
tsconfig.json being ignored.

### ISSUE THREAD

**Issue by nickwebha** [vikpe/react-webpack-typescript-starter#46]
If I clone the repo, run `yarn install`, run `yarn build`, everything runs great.

So I decided to start configuring TypeScript to be stricter by adding `"strict": true` to `compilerOptions` in `tsconfig.json`. It would not take. After trying a few things I decided to just type gibberish into `tsconfig.json`, intentionally breaking it. It did not break. I tried removing halves of sections and adding extra brackets intentionally creating an invalid JSON file and it did not break.

I think `tsconfig.json` is being ignored.

I have been reading more about webpack and TypeScript and can not figure out why this might be happening. I suspect a deeper  problem but do not know enough about it.

**Comment by vikpe** [comment]
@nickwebha thanks for the feedback, i'll investigate it!

**Comment by vikpe** [comment]
My guess is `tsconfig.json` is ignored since [I swapped awesome-typescript-loader in favor of babel-loader](https://github.com/vikpe/react-webpack-typescript-starter/commit/c7cc039011132895a2c3b4f206ea3acf000f5b52#diff-e9f352bd7024d5ab9bd584582153dae05829a4f182e06b91b00c400bfe294c11L14-L21).

I do prefer default/less configuration. But you should of course be able to set any options you like. Will try to find a fix asap.

**Comment by vikpe** [comment]
From the [babel docs](https://babeljs.io/docs/en/babel-plugin-transform-typescript#caveats)
> Changes to your tsconfig.json are not reflected in babel. The build process will always behave as though isolatedModules is turned on, there are Babel-native [alternative ways to set a lot of the tsconfig.json options](https://babeljs.io/docs/en/babel-plugin-transform-typescript#typescript-compiler-options) however.
